#!/usr/bin/env ruby

require 'open-uri'
require 'json'
require 'fileutils'
require 'pathname'

url     = ARGV.shift or abort "no config url given"
twitter = ARGV.shift or abort "no twitter handle given"
source  = ARGV.shift or abort "no source name given"
lang    = ARGV.shift or abort "no wiki lang given"

conf   = JSON.parse(open(url).read)
ranges = conf['ranges'] || conf['accounts'].first['ranges']

case lang
when 'en.public'
  lang = 'en'
  old  = true
else
  old = false
end

year_range = old ? '2002-2010' : 'latest'
path = Pathname.new("../../#{twitter}/#{lang}/#{year_range}").expand_path(__FILE__)
path.mkpath

ranges_path = path.join('ranges.json')
data_path   = path.join('data.csv')
html_path   = path.join('index.html')

ranges_path.open('w') { |io| io << {ranges: ranges}.to_json }

if old
  query = `scripts/generate-bigquery.rb --old #{ranges_path} 2>&1`
else
  query = `scripts/generate-bigquery.rb --wiki #{lang} #{ranges_path} 2>&1`
end

abort query unless $?.success?

IO.popen("pbcopy", "w") { |io| io << query; io.close }

puts "Execute this query:\n\n #{query} \n\n"
puts "Download results to: \n\n\t #{data_path} \n\n"
puts "Then press any key"

STDIN.gets || abort

#html = `scripts/generate-html.rb --erb scripts/template-ru.html.erb --source '#{source}' --wiki #{lang} --twitter '#{twitter}' #{data_path} #{ranges_path} 2>&1`
html = `scripts/generate-html.rb --source '#{source}' --wiki #{lang} --twitter '#{twitter}' #{data_path} #{ranges_path} 2>&1`
abort html unless $?.success?
html_path.open('w') { |io| io << html }

puts "Add to index.html: \n\n"

if `which open` && $?.success?
  `open http://localhost:8080/#{twitter}/#{lang}/#{year_range}/`
end

