#!/usr/bin/env ruby

require 'open-uri'
require 'json'
require 'fileutils'
require 'pathname'

url = ARGV.shift or abort "no config url given"
twitter = ARGV.shift or abort "no twitter handle given"
source = ARGV.shift or abort "no source name given"

conf = JSON.parse(open(url).read)
ranges = conf['ranges'] || conf['accounts'].first['ranges']

path = Pathname.new("../../#{twitter}/2002-2010").expand_path(__FILE__)
path.mkpath

ranges_path = path.join('ranges.json')
data_path   = path.join('data.csv')
html_path   = path.join('index.html')

ranges_path.open('w') { |io| io << {ranges: ranges}.to_json }

query = `scripts/generate-bigquery.rb #{ranges_path} 2>&1`
abort query unless $?.success?

puts "Execute this query:\n\n #{query} \n\n"
puts "Download results to: \n\n\t #{data_path} \n\n"
puts "Then press any key"

STDIN.gets || abort

html = `scripts/generate-html.rb --source '#{source}' --twitter '#{twitter}' #{data_path} #{ranges_path} 2>&1`
abort html unless $?.success?
html_path.open('w') { |io| io << html }

if `which open` && $?.success?
  `open http://localhost:8080/#{twitter}/2002-2010/`
end

